hey-url-challenge-code-dotnet/Models/LogUrl.cs
using System;

namespace hey_url_challenge_code_dotnet.Models
{
    public class LogUrl
    {
        public int IdLog { get; set; }
        public int IdUrl { get; set; }
        public string UserPlatform { get; set; }

        public string Browser { get; set; }

        public DateTime LogDate { get; set; }
    }
}

hey-url-challenge-code-dotnet/Models/Url.cs
using System;
namespace hey_url_challenge_code_dotnet.Models
{
    public class Url
    {
        public int IdUrl { get; set; }
        public string ShortUrl { get; set; }

        public string OriginalUrl { get; set; }
        public int CountAccess { get; set; }
        public DateTime UrlDate { get; set; }
    }
}

hey-url-challenge-code-dotnet/ViewModels/ErrorViewModel.cs
namespace HeyUrlChallengeCodeDotnet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

hey-url-challenge-code-dotnet/ViewModels/HomeViewModel.cs
using System.Collections.Generic;
using hey_url_challenge_code_dotnet.Models;

namespace hey_url_challenge_code_dotnet.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Url> Urls { get; set; }
        public Url NewUrl { get; set; }
    }
}

hey-url-challenge-code-dotnet/ViewModels/ShowViewModel.cs
using System.Collections.Generic;
using hey_url_challenge_code_dotnet.Models;

namespace hey_url_challenge_code_dotnet.ViewModels
{
    public class ShowViewModel
    {
        public Url Url { get; set; }
        public Dictionary<string, int> DailyClicks { get; set; }
        public Dictionary<string, int> BrowseClicks { get; set; }
        public Dictionary<string, int> PlatformClicks { get; set; }
    }
}

hey-url-challenge-code-dotnet/Controllers/UrlRestController.cs
using hey_url_challenge_code_dotnet.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace hey_url_challenge_code_dotnet.Controllers
{
    [Route("/[controller]")]
    [ApiController]
    public class UrlRestController : Controller
    {
        private IUrlGenerics _urlGenerics;
        public UrlRestController(IUrlGenerics urlGenerics)
        {
            _urlGenerics = urlGenerics;
        }


        [HttpGet("Get10LastUrl")]
        public IActionResult Get10LastURL()
        {
            try
            {
                var ls = _urlGenerics.GetAll().Result.ToList().Take(10).OrderByDescending(x => x.UrlDate);
                return Ok(ls);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}

hey-url-challenge-code-dotnet/Controllers/UrlsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using hey_url_challenge_code_dotnet.Interfaces;
using hey_url_challenge_code_dotnet.Models;
using hey_url_challenge_code_dotnet.Services;
using hey_url_challenge_code_dotnet.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Shyjus.BrowserDetection;

namespace HeyUrlChallengeCodeDotnet.Controllers
{
    [Route("/")]
    public class UrlsController : Controller
    {
        private readonly ILogger<UrlsController> _logger;
        private static readonly Random getrandom = new Random();
        private readonly IBrowserDetector browserDetector;
        private readonly IFixUrlService _fixUrlService;
        private readonly IUrlGenerics _urlGenerics;
        private readonly ILogUrlGenerics _logUrlGenerics;

        public UrlsController(ILogger<UrlsController> logger, IBrowserDetector browserDetector, IFixUrlService fixUrlService, IUrlGenerics urlGenerics, ILogUrlGenerics logUrlGenerics)
        {
            this.browserDetector = browserDetector;
            _logger = logger;
            _fixUrlService = fixUrlService;
            _urlGenerics = urlGenerics;
            _logUrlGenerics = logUrlGenerics;
        }

        public async Task <IActionResult> Index()
        {
            var urls = await _fixUrlService.GetAll();
            return View(new HomeViewModel { Urls = urls });
          
        }

        [HttpPost]
        public async Task<IActionResult> Create( HomeViewModel model)
        {
            if (model is not null)
            {
                if (!Uri.IsWellFormedUriString(model.NewUrl.OriginalUrl, UriKind.Absolute))
                {
                    TempData["Notice"] = "URL Specified is not valid.";
                }
                else
                {
                    await this._fixUrlService.CreateFixUrl(model.NewUrl.OriginalUrl);
                }
            }
            else
            {
                throw new ArgumentNullException(nameof(model));
            }
            return RedirectToAction("Index");
        }

        [Route("urls/{url}")]
        public async Task<IActionResult> Visit(string url)
        {
            try
            {
                await this._fixUrlService.CreateLog(url, browserDetector.Browser.Name, browserDetector.Browser.OS);
                var urlOld = await _urlGenerics.GetUrlByFixUrl(url);
                return Redirect(urlOld.OriginalUrl);
            }catch (Exception)
            {
                return NotFound();
            }
        }

        [Route("urls/Charts/{url}")]
        public async Task<IActionResult> Show(string url) 
        {
            var urlDetails = (List<LogUrl>)await _logUrlGenerics.GetLogsUrlByFixUrl(url);
            var urlPri = (Url)await _urlGenerics.GetUrlByFixUrl(url);

            Dictionary<string, int> DailyClicks = new Dictionary<string, int>();
            Dictionary<string, int> Platform = new Dictionary<string, int>();
            Dictionary<string, int> Browser = new Dictionary<string, int>();


            var lstOS = from r in urlDetails
                        orderby r.UserPlatform
                        group r by r.UserPlatform into plf
                        select new { key = plf.Key, plat = plf.Count() };

            var lstBr = from r in urlDetails
                        orderby r.Browser
                        group r by r.Browser into brs
                        select new { key = brs.Key, plat = brs.Count() };

            var lstDay = from r in urlDetails
                        where r.LogDate.Month == DateTime.UtcNow.Month
                        orderby r.LogDate.Day
                        group r by r.LogDate.Day into dlf
                        select new { key = dlf.Key, plat = dlf.Count() };

            foreach (var item in lstOS)
            {
                Platform.Add(item.key, item.plat);
            }
            foreach (var item in lstBr)
            {
                Browser.Add(item.key, item.plat);
            }
            foreach (var item in lstDay)
            {
                DailyClicks.Add(item.key.ToString(), item.plat);
            }

            return View(new ShowViewModel
            {
                Url = urlPri,
                DailyClicks = DailyClicks,
                BrowseClicks = Browser,
                PlatformClicks = Platform
            });
        }
    }
}

hey-url-challenge-code-dotnet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/materialize/css/materialize.min.css" />
    <script src="~/lib/materialize/js/materialize.min.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>
<body>
    <nav>
        <div class="nav-wrapper">
            <a class="brand-logo" asp-area="" asp-controller="Urls" asp-action="Index">HeyURL!</a>
        </div>
    </nav>
    <main role="main" class="container">
        @RenderBody()
    </main>
</body>
</html>

hey-url-challenge-code-dotnet/Views/Urls/Index.cshtml
@model hey_url_challenge_code_dotnet.ViewModels.HomeViewModel

@{
    ViewData["Title"] = "Home Page";
}

@if (TempData["Notice"] is not null)
{
    <div class="card-panel notice deep-orange">@TempData["Notice"]</div>
}

<div class="row">
    <div class="col m12">
        <form asp-action="Create">
            <div class="card">
                <div class="card-content">
                    <div class="row">
                        <div class="col m8 offset-m2 center-align">
                            <span class="card-title">Create a new short URL</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col m6 offset-m2">
                            @Html.TextBoxFor(i=>i.NewUrl.OriginalUrl, null, new{@class="validate form-control", placeHolder="Your URL Here..."})
                        </div>
                        <div class="col m2">
                            <button type="submit" class="btn">Shorten URL</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<table class="table highlight">
    <thead>
        <tr>
            <th scope="col">Short URL</th>
            <th scope="col">Original URL</th>
            <th scope="col">Created</th>
            <th scope="col">Clicks Count</th>
            <th scope="col">Stats</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var url in Model.Urls)
        {
            <tr>
                <th scope="row">@Html.ActionLink($"https://localhost:5001/{url.ShortUrl}",url.ShortUrl, null)</th>
                <td>@Html.ActionLink(url.OriginalUrl, null, null)</td>
                <td>@url.UrlDate.ToString("MMM dd, yyyy")</td>
                <td>@url.CountAccess </td>
                <td>
                    <a href=@string.Format("/urls/Charts/{0}", url.ShortUrl)>
                        <svg class="octicon octicon-graph" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true">
                            <path fill-rule="evenodd" d="M16 14v1H0V0h1v14h15zM5 13H3V8h2v5zm4 0H7V3h2v10zm4 0h-2V6h2v7z"></path>
                        </svg>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

hey-url-challenge-code-dotnet/Views/Urls/Show.cshtml
@model hey_url_challenge_code_dotnet.ViewModels.ShowViewModel

@{
    ViewBag.Title = "Show";
    Layout = "_Layout";
}

<div class="row">
    <div class="col s12">
      <ul class="card-panel collection with-header">
        <li class="collection-header">
          <h4>
            Stats for <a href="@Model.Url.ShortUrl">@Model.Url.ShortUrl</a>
          </h4>
        </li>
        <li class="collection-item">@Model.Url.UrlDate.ToString("MMM dd, yyyy")</li>
        <li class="collection-item">
          Original URL: @Model.Url.OriginalUrl
        </li>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <div class="card-panel">
        <div id="total-clicks-chart"></div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col s6">
      <div class="card-panel">
        <div id="platforms-chart"></div>
      </div>
    </div>

    <div class="col s6">
      <div class="card-panel">
        <div id="browsers-chart"></div>
      </div>
    </div>
  </div>

  <script>
    google.charts.load('current', {packages: ['corechart']});
    google.charts.setOnLoadCallback(drawCharts);
    function drawTotalClicksChart() {
      var data = google.visualization.arrayToDataTable([
        ['day', 'clicks'],
      ].concat(@Json.Serialize(Model.DailyClicks.Select(e => new object[] { e.Key, e.Value }))));
      var options = {
        title: 'total clicks',
        haxis: {
          title: 'day of month'
        },
        vaxis: {
          title: 'clicks'
        }
      };
      var chart = new google.visualization.AreaChart(
        document.getElementById('total-clicks-chart')
      );
      chart.draw(data, options);
    }
    function drawBrowsersChart() {
      var data = google.visualization.arrayToDataTable([
        ['browser', 'clicks'],
      ].concat(@Json.Serialize(Model.BrowseClicks.Select(e => new object[] { e.Key, e.Value }))));
      var options = {
        title: 'Browsers'
      };
      var chart = new google.visualization.PieChart(
        document.getElementById('browsers-chart')
      );
      chart.draw(data, options);
    }
    function drawPlatformsChart() {
      var data = google.visualization.arrayToDataTable([
        ['platform', 'clicks'],
      ].concat(@Json.Serialize(Model.PlatformClicks.Select(e => new object[] { e.Key, e.Value }))));
      var options = {
        title: 'Platform'
      };
      var chart = new google.visualization.PieChart(
        document.getElementById('platforms-chart')
      );
      chart.draw(data, options);
    }
    function drawCharts() {
      drawTotalClicksChart();
      drawBrowsersChart();
      drawPlatformsChart();
    }
  </script>